apiVersion: v1
kind: ConfigMap
metadata:
  name: <NAME OF THE ConfigMap>
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: 192.168.3.113
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: mySecret
type: Opaque
data:
  <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: bXlwYXNzd29yZA==