apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: "192.168.17.46"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==
